//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportNews247.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public string id { get; set; }
        public string id_dm { get; set; }
        public string id_user { get; set; }
        public string tieu_de { get; set; }
        public string img { get; set; }
        public string tom_tat { get; set; }
        public string noi_dung { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
        public Nullable<int> trang_thai { get; set; }
    
        public virtual DanhMucTin DanhMucTin { get; set; }
        public virtual User User { get; set; }
    }
}
